TRAINING_DATA_PATH = "../data/train.csv"
TEST_DATA_PATH = "../data/test.csv"
DATA_PATH = "../data"

ONE_HOT_ENCODER_LANGUAGE = "../resources"
MODEL_PATH = "../resources/gcn_models"

NODE_FEATURES = [
    "eccentricity",
    "degree_cent",
    "harmoni_cent",
    "betweeness_cent",
    "page_cent",
    "eigen_cent",
    "closeness_cent",
    "katz_cent",
    "information_cent",
    "load_centrality",
    "subgraph_cent",
    "comm_betweenness",
    "current_flow_closeness",
    "current_flow_betweenness",
    "second_order_cent",
    "degree",
    "avg_shortest_path_length",
    "effective_size",
    "vote_rank_score",
    "is_leaf",
    "largest_component_removed",
    "num_subtrees_removed",
    "subtree_size_variance",
    "participation_diameter",
    "radiality",
    "neighbor_degree_mean",
    "neighbor_degree_max",
    "neighbor_degree_min",
    "num_leaf_neighbors",
    "node_step_removal",
    "max_height",
    'avg_distance_to_all_nodes',
    'max_distance_to_any_node',
    'avg_distance_to_leaf_nodes',
    'std_distance_to_leaf_nodes',
    'distance_to_farthest_leaf',
    'distance_to_nearest_leaf',
    'max_subtree_size',
    'min_subtree_size',
    'subtree_size_balance',
    'num_subtrees',
    'subtree_size_std',
    'max_subtree_depth',
    'min_subtree_depth',
    'subtree_depth_balance',
    'subtree_depth_std',
    'is_centroid',
    'leaf_density',
    # Bucketing features
    'eccentricity_bucket',
    'degree_cent_bucket',
    'harmoni_cent_bucket',
    'betweeness_cent_bucket',
    'page_cent_bucket',
    'eigen_cent_bucket',
    'closeness_cent_bucket',
    'katz_cent_bucket',
    'information_cent_bucket',
    'load_centrality_bucket',
    'subgraph_cent_bucket',
    'comm_betweenness_bucket',
    'current_flow_closeness_bucket',
    'current_flow_betweenness_bucket',
    'second_order_cent_bucket',
    'degree_bucket',
    'avg_shortest_path_length_bucket',
    'effective_size_bucket',
    'vote_rank_score_bucket',
    'is_leaf_bucket',
    'largest_component_removed_bucket',
    'num_subtrees_removed_bucket',
    'subtree_size_variance_bucket',
    'participation_diameter_bucket',
    'radiality_bucket',
    'neighbor_degree_mean_bucket',
    'neighbor_degree_max_bucket',
    'neighbor_degree_min_bucket',
    'num_leaf_neighbors_bucket',
    'node_step_removal_bucket',
    'max_height_bucket',
    'avg_distance_to_all_nodes_bucket',
    'max_distance_to_any_node_bucket',
    'avg_distance_to_leaf_nodes_bucket',
    'std_distance_to_leaf_nodes_bucket',
    'distance_to_farthest_leaf_bucket',
    'distance_to_nearest_leaf_bucket',
    'max_subtree_size_bucket',
    'min_subtree_size_bucket',
    'subtree_size_balance_bucket',
    'num_subtrees_bucket',
    'subtree_size_std_bucket',
    'max_subtree_depth_bucket',
    'min_subtree_depth_bucket',
    'subtree_depth_balance_bucket',
    'subtree_depth_std_bucket',
    'is_centroid_bucket',
    'leaf_density_bucket',
    # Descriptive statistics features
    'eccentricity_mean', 'eccentricity_std', 'eccentricity_min', 'eccentricity_max', 'eccentricity_median', 'eccentricity_skew', 'eccentricity_q1', 'eccentricity_q2', 'eccentricity_q3', 'eccentricity_iqr',
    'degree_cent_mean', 'degree_cent_std', 'degree_cent_min', 'degree_cent_max', 'degree_cent_median', 'degree_cent_skew', 'degree_cent_q1', 'degree_cent_q2', 'degree_cent_q3', 'degree_cent_iqr',
    'harmoni_cent_mean', 'harmoni_cent_std', 'harmoni_cent_min', 'harmoni_cent_max', 'harmoni_cent_median', 'harmoni_cent_skew', 'harmoni_cent_q1', 'harmoni_cent_q2', 'harmoni_cent_q3', 'harmoni_cent_iqr',
    'betweeness_cent_mean', 'betweeness_cent_std', 'betweeness_cent_min', 'betweeness_cent_max', 'betweeness_cent_median', 'betweeness_cent_skew', 'betweeness_cent_q1', 'betweeness_cent_q2', 'betweeness_cent_q3', 'betweeness_cent_iqr',
    'page_cent_mean', 'page_cent_std', 'page_cent_min', 'page_cent_max', 'page_cent_median', 'page_cent_skew', 'page_cent_q1', 'page_cent_q2', 'page_cent_q3', 'page_cent_iqr',
    'eigen_cent_mean', 'eigen_cent_std', 'eigen_cent_min', 'eigen_cent_max', 'eigen_cent_median', 'eigen_cent_skew', 'eigen_cent_q1', 'eigen_cent_q2', 'eigen_cent_q3', 'eigen_cent_iqr',
    'closeness_cent_mean', 'closeness_cent_std', 'closeness_cent_min', 'closeness_cent_max', 'closeness_cent_median', 'closeness_cent_skew', 'closeness_cent_q1', 'closeness_cent_q2', 'closeness_cent_q3', 'closeness_cent_iqr',
    'katz_cent_mean', 'katz_cent_std', 'katz_cent_min', 'katz_cent_max', 'katz_cent_median', 'katz_cent_skew', 'katz_cent_q1', 'katz_cent_q2', 'katz_cent_q3', 'katz_cent_iqr',
    'information_cent_mean', 'information_cent_std', 'information_cent_min', 'information_cent_max', 'information_cent_median', 'information_cent_skew', 'information_cent_q1', 'information_cent_q2', 'information_cent_q3', 'information_cent_iqr',
    'load_centrality_mean', 'load_centrality_std', 'load_centrality_min', 'load_centrality_max', 'load_centrality_median', 'load_centrality_skew', 'load_centrality_q1', 'load_centrality_q2', 'load_centrality_q3', 'load_centrality_iqr',
    'subgraph_cent_mean', 'subgraph_cent_std', 'subgraph_cent_min', 'subgraph_cent_max', 'subgraph_cent_median', 'subgraph_cent_skew', 'subgraph_cent_q1', 'subgraph_cent_q2', 'subgraph_cent_q3', 'subgraph_cent_iqr',
    'comm_betweenness_mean', 'comm_betweenness_std', 'comm_betweenness_min', 'comm_betweenness_max', 'comm_betweenness_median', 'comm_betweenness_skew', 'comm_betweenness_q1', 'comm_betweenness_q2', 'comm_betweenness_q3', 'comm_betweenness_iqr',
    'current_flow_closeness_mean', 'current_flow_closeness_std', 'current_flow_closeness_min', 'current_flow_closeness_max', 'current_flow_closeness_median', 'current_flow_closeness_skew', 'current_flow_closeness_q1', 'current_flow_closeness_q2', 'current_flow_closeness_q3', 'current_flow_closeness_iqr',
    'current_flow_betweenness_mean', 'current_flow_betweenness_std', 'current_flow_betweenness_min', 'current_flow_betweenness_max', 'current_flow_betweenness_median', 'current_flow_betweenness_skew', 'current_flow_betweenness_q1', 'current_flow_betweenness_q2', 'current_flow_betweenness_q3', 'current_flow_betweenness_iqr',
    'second_order_cent_mean', 'second_order_cent_std', 'second_order_cent_min', 'second_order_cent_max', 'second_order_cent_median', 'second_order_cent_skew', 'second_order_cent_q1', 'second_order_cent_q2', 'second_order_cent_q3', 'second_order_cent_iqr',
    'degree_mean', 'degree_std', 'degree_min', 'degree_max', 'degree_median', 'degree_skew', 'degree_q1', 'degree_q2', 'degree_q3', 'degree_iqr',
    'avg_shortest_path_length_mean', 'avg_shortest_path_length_std', 'avg_shortest_path_length_min', 'avg_shortest_path_length_max', 'avg_shortest_path_length_median', 'avg_shortest_path_length_skew', 'avg_shortest_path_length_q1', 'avg_shortest_path_length_q2', 'avg_shortest_path_length_q3', 'avg_shortest_path_length_iqr',
    'effective_size_mean', 'effective_size_std', 'effective_size_min', 'effective_size_max', 'effective_size_median', 'effective_size_skew', 'effective_size_q1', 'effective_size_q2', 'effective_size_q3', 'effective_size_iqr',
    'vote_rank_score_mean', 'vote_rank_score_std', 'vote_rank_score_min', 'vote_rank_score_max', 'vote_rank_score_median', 'vote_rank_score_skew', 'vote_rank_score_q1', 'vote_rank_score_q2', 'vote_rank_score_q3', 'vote_rank_score_iqr',
    'is_leaf_mean', 'is_leaf_std', 'is_leaf_min', 'is_leaf_max', 'is_leaf_median', 'is_leaf_skew', 'is_leaf_q1', 'is_leaf_q2', 'is_leaf_q3', 'is_leaf_iqr',
    'largest_component_removed_mean', 'largest_component_removed_std', 'largest_component_removed_min', 'largest_component_removed_max', 'largest_component_removed_median', 'largest_component_removed_skew', 'largest_component_removed_q1', 'largest_component_removed_q2', 'largest_component_removed_q3', 'largest_component_removed_iqr',
    'num_subtrees_removed_mean', 'num_subtrees_removed_std', 'num_subtrees_removed_min', 'num_subtrees_removed_max', 'num_subtrees_removed_median', 'num_subtrees_removed_skew', 'num_subtrees_removed_q1', 'num_subtrees_removed_q2', 'num_subtrees_removed_q3', 'num_subtrees_removed_iqr',
    'subtree_size_variance_mean', 'subtree_size_variance_std', 'subtree_size_variance_min', 'subtree_size_variance_max', 'subtree_size_variance_median', 'subtree_size_variance_skew', 'subtree_size_variance_q1', 'subtree_size_variance_q2', 'subtree_size_variance_q3', 'subtree_size_variance_iqr',
    'participation_diameter_mean', 'participation_diameter_std', 'participation_diameter_min', 'participation_diameter_max', 'participation_diameter_median', 'participation_diameter_skew', 'participation_diameter_q1', 'participation_diameter_q2', 'participation_diameter_q3', 'participation_diameter_iqr',
    'radiality_mean', 'radiality_std', 'radiality_min', 'radiality_max', 'radiality_median', 'radiality_skew', 'radiality_q1', 'radiality_q2', 'radiality_q3', 'radiality_iqr',
    'neighbor_degree_mean_mean', 'neighbor_degree_mean_std', 'neighbor_degree_mean_min', 'neighbor_degree_mean_max', 'neighbor_degree_mean_median', 'neighbor_degree_mean_skew', 'neighbor_degree_mean_q1', 'neighbor_degree_mean_q2', 'neighbor_degree_mean_q3', 'neighbor_degree_mean_iqr',
    'neighbor_degree_max_mean', 'neighbor_degree_max_std', 'neighbor_degree_max_min', 'neighbor_degree_max_max', 'neighbor_degree_max_median', 'neighbor_degree_max_skew', 'neighbor_degree_max_q1', 'neighbor_degree_max_q2', 'neighbor_degree_max_q3', 'neighbor_degree_max_iqr',
    'neighbor_degree_min_mean', 'neighbor_degree_min_std', 'neighbor_degree_min_min', 'neighbor_degree_min_max', 'neighbor_degree_min_median', 'neighbor_degree_min_skew', 'neighbor_degree_min_q1', 'neighbor_degree_min_q2', 'neighbor_degree_min_q3', 'neighbor_degree_min_iqr',
    'num_leaf_neighbors_mean', 'num_leaf_neighbors_std', 'num_leaf_neighbors_min', 'num_leaf_neighbors_max', 'num_leaf_neighbors_median', 'num_leaf_neighbors_skew', 'num_leaf_neighbors_q1', 'num_leaf_neighbors_q2', 'num_leaf_neighbors_q3', 'num_leaf_neighbors_iqr',
    'node_step_removal_mean', 'node_step_removal_std', 'node_step_removal_min', 'node_step_removal_max', 'node_step_removal_median', 'node_step_removal_skew', 'node_step_removal_q1', 'node_step_removal_q2', 'node_step_removal_q3', 'node_step_removal_iqr',
    'max_height_mean', 'max_height_std', 'max_height_min', 'max_height_max', 'max_height_median', 'max_height_skew', 'max_height_q1', 'max_height_q2', 'max_height_q3', 'max_height_iqr',
    'avg_distance_to_all_nodes_mean', 'avg_distance_to_all_nodes_std', 'avg_distance_to_all_nodes_min', 'avg_distance_to_all_nodes_max', 'avg_distance_to_all_nodes_median', 'avg_distance_to_all_nodes_skew', 'avg_distance_to_all_nodes_q1', 'avg_distance_to_all_nodes_q2', 'avg_distance_to_all_nodes_q3', 'avg_distance_to_all_nodes_iqr',
    'max_distance_to_any_node_mean', 'max_distance_to_any_node_std', 'max_distance_to_any_node_min', 'max_distance_to_any_node_max', 'max_distance_to_any_node_median', 'max_distance_to_any_node_skew', 'max_distance_to_any_node_q1', 'max_distance_to_any_node_q2', 'max_distance_to_any_node_q3', 'max_distance_to_any_node_iqr',
    'avg_distance_to_leaf_nodes_mean', 'avg_distance_to_leaf_nodes_std', 'avg_distance_to_leaf_nodes_min', 'avg_distance_to_leaf_nodes_max', 'avg_distance_to_leaf_nodes_median', 'avg_distance_to_leaf_nodes_skew', 'avg_distance_to_leaf_nodes_q1', 'avg_distance_to_leaf_nodes_q2', 'avg_distance_to_leaf_nodes_q3', 'avg_distance_to_leaf_nodes_iqr',
    'std_distance_to_leaf_nodes_mean', 'std_distance_to_leaf_nodes_std', 'std_distance_to_leaf_nodes_min', 'std_distance_to_leaf_nodes_max', 'std_distance_to_leaf_nodes_median', 'std_distance_to_leaf_nodes_skew', 'std_distance_to_leaf_nodes_q1', 'std_distance_to_leaf_nodes_q2', 'std_distance_to_leaf_nodes_q3', 'std_distance_to_leaf_nodes_iqr',
    'distance_to_farthest_leaf_mean', 'distance_to_farthest_leaf_std', 'distance_to_farthest_leaf_min', 'distance_to_farthest_leaf_max', 'distance_to_farthest_leaf_median', 'distance_to_farthest_leaf_skew', 'distance_to_farthest_leaf_q1', 'distance_to_farthest_leaf_q2', 'distance_to_farthest_leaf_q3', 'distance_to_farthest_leaf_iqr',
    'distance_to_nearest_leaf_mean', 'distance_to_nearest_leaf_std', 'distance_to_nearest_leaf_min', 'distance_to_nearest_leaf_max', 'distance_to_nearest_leaf_median', 'distance_to_nearest_leaf_skew', 'distance_to_nearest_leaf_q1', 'distance_to_nearest_leaf_q2', 'distance_to_nearest_leaf_q3', 'distance_to_nearest_leaf_iqr',
    'max_subtree_size_mean', 'max_subtree_size_std', 'max_subtree_size_min', 'max_subtree_size_max', 'max_subtree_size_median', 'max_subtree_size_skew', 'max_subtree_size_q1', 'max_subtree_size_q2', 'max_subtree_size_q3', 'max_subtree_size_iqr',
    'min_subtree_size_mean', 'min_subtree_size_std', 'min_subtree_size_min', 'min_subtree_size_max', 'min_subtree_size_median', 'min_subtree_size_skew', 'min_subtree_size_q1', 'min_subtree_size_q2', 'min_subtree_size_q3', 'min_subtree_size_iqr',
    'subtree_size_balance_mean', 'subtree_size_balance_std', 'subtree_size_balance_min', 'subtree_size_balance_max', 'subtree_size_balance_median', 'subtree_size_balance_skew', 'subtree_size_balance_q1', 'subtree_size_balance_q2', 'subtree_size_balance_q3', 'subtree_size_balance_iqr',
    'num_subtrees_mean', 'num_subtrees_std', 'num_subtrees_min', 'num_subtrees_max', 'num_subtrees_median', 'num_subtrees_skew', 'num_subtrees_q1', 'num_subtrees_q2', 'num_subtrees_q3', 'num_subtrees_iqr',
    'subtree_size_std_mean', 'subtree_size_std_std', 'subtree_size_std_min', 'subtree_size_std_max', 'subtree_size_std_median', 'subtree_size_std_skew', 'subtree_size_std_q1', 'subtree_size_std_q2', 'subtree_size_std_q3', 'subtree_size_std_iqr',
    'max_subtree_depth_mean', 'max_subtree_depth_std', 'max_subtree_depth_min', 'max_subtree_depth_max', 'max_subtree_depth_median', 'max_subtree_depth_skew', 'max_subtree_depth_q1', 'max_subtree_depth_q2', 'max_subtree_depth_q3', 'max_subtree_depth_iqr',
    'min_subtree_depth_mean', 'min_subtree_depth_std', 'min_subtree_depth_min', 'min_subtree_depth_max', 'min_subtree_depth_median', 'min_subtree_depth_skew', 'min_subtree_depth_q1', 'min_subtree_depth_q2', 'min_subtree_depth_q3', 'min_subtree_depth_iqr',
    'subtree_depth_balance_mean', 'subtree_depth_balance_std', 'subtree_depth_balance_min', 'subtree_depth_balance_max', 'subtree_depth_balance_median', 'subtree_depth_balance_skew', 'subtree_depth_balance_q1', 'subtree_depth_balance_q2', 'subtree_depth_balance_q3', 'subtree_depth_balance_iqr',
    'subtree_depth_std_mean', 'subtree_depth_std_std', 'subtree_depth_std_min', 'subtree_depth_std_max', 'subtree_depth_std_median', 'subtree_depth_std_skew', 'subtree_depth_std_q1', 'subtree_depth_std_q2', 'subtree_depth_std_q3', 'subtree_depth_std_iqr',
    'is_centroid_mean', 'is_centroid_std', 'is_centroid_min', 'is_centroid_max', 'is_centroid_median', 'is_centroid_skew', 'is_centroid_q1', 'is_centroid_q2', 'is_centroid_q3', 'is_centroid_iqr',
    'leaf_density_mean', 'leaf_density_std', 'leaf_density_min', 'leaf_density_max', 'leaf_density_median', 'leaf_density_skew', 'leaf_density_q1', 'leaf_density_q2', 'leaf_density_q3', 'leaf_density_iqr'
]


LANGUAGE_TO_GROUP = {
    "English": "Germanic",
    "German": "Germanic",
    "Swedish": "Germanic",
    "Icelandic": "Germanic",
    "French": "Romance",
    "Spanish": "Romance",
    "Italian": "Romance",
    "Portuguese": "Romance",
    "Galician": "Romance",
    "Russian": "Slavic",
    "Polish": "Slavic",
    "Czech": "Slavic",
    "Finnish": "Uralic",
    "Turkish": "Turkic",
    "Hindi": "Indo-Aryan",
    "Japanese": "Japonic",
    "Korean": "Koreanic",
    "Chinese": "Sino-Tibetan",
    "Indonesian": "Austronesian",
    "Arabic": "Semitic",
    "Thai": "Kra-Dai"
}


LANGUAGE_TO_GROUP_NEW = {
    "Arabic": "Afro-Asiatic",
    "Indonesian": "Austronesian",
    "Korean": "Koreanic",
    "Czech": "Indo-European",
    "English": "Indo-European",
    "French": "Indo-European",
    "Galician": "Indo-European",
    "German": "Indo-European",
    "Hindi": "Indo-European",
    "Icelandic": "Indo-European",
    "Italian": "Indo-European",
    "Polish": "Indo-European",
    "Portuguese": "Indo-European",
    "Russian": "Indo-European",
    "Spanish": "Indo-European",
    "Swedish": "Indo-European",
    "Japanese": "Japonic",
    "Chinese": "Sino-Tibetan",
    "Thai": "Tai-Kadai",
    "Turkish": "Turkic",
    "Finnish": "Uralic"
}

DOMINANT_ORDER_GROUPED = {
    "VSO": ["Arabic"],
    "SVO": [
        "Indonesian", "Czech", "English", "French", "Galician",
        "German", "Icelandic", "Italian", "Polish", "Portuguese",
        "Russian", "Spanish", "Swedish", "Chinese", "Thai", "Finnish"
    ],
    "SOV": ["Korean", "Hindi", "Japanese", "Turkish", "German"]
}

TRAIN_DROP_COLS = ['sentence','is_root','node_number','kfold','language','language_group',
'avg_distance_to_all_nodes',
 'avg_distance_to_all_nodes_bucket',
 'avg_distance_to_all_nodes_iqr',
 'avg_distance_to_all_nodes_mean',
 'avg_distance_to_all_nodes_median',
 'avg_distance_to_all_nodes_q1',
 'avg_distance_to_all_nodes_q2',
 'avg_distance_to_all_nodes_q3',
 'avg_distance_to_all_nodes_skew',
 'avg_distance_to_all_nodes_std',
 'avg_distance_to_leaf_nodes',
 'avg_distance_to_leaf_nodes_q2',
 'avg_shortest_path_length',
 'avg_shortest_path_length_bucket',
 'avg_shortest_path_length_iqr',
 'avg_shortest_path_length_q1',
 'avg_shortest_path_length_q2',
 'avg_shortest_path_length_q3',
 'avg_shortest_path_length_std',
 'betweeness_cent',
 'betweeness_cent_bucket',
 'betweeness_cent_iqr',
 'betweeness_cent_mean',
 'betweeness_cent_median',
 'betweeness_cent_q1',
 'betweeness_cent_q2',
 'betweeness_cent_q3',
 'betweeness_cent_skew',
 'closeness_cent',
 'closeness_cent_bucket',
 'closeness_cent_median',
 'closeness_cent_q2',
 'comm_betweenness',
 'comm_betweenness_bucket',
 'comm_betweenness_iqr',
 'comm_betweenness_mean',
 'comm_betweenness_median',
 'comm_betweenness_q1',
 'comm_betweenness_q2',
 'comm_betweenness_q3',
 'comm_betweenness_skew',
 'comm_betweenness_std',
 #'current_flow_betweenness',
 'current_flow_betweenness_iqr',
 'current_flow_betweenness_mean',
 'current_flow_betweenness_median',
 'current_flow_betweenness_q1',
 'current_flow_betweenness_q2',
 'current_flow_betweenness_q3',
 'current_flow_betweenness_skew',
 'current_flow_betweenness_std',
 'current_flow_closeness',
 'current_flow_closeness_bucket',
 'current_flow_closeness_iqr',
 'current_flow_closeness_max',
 'current_flow_closeness_mean',
 'current_flow_closeness_median',
 'current_flow_closeness_q1',
 'current_flow_closeness_q2',
 'current_flow_closeness_q3',
 'current_flow_closeness_skew',
 'current_flow_closeness_std',
 'degree_bucket',
 'degree_cent',
 'degree_cent_iqr',
 'degree_cent_mean',
 'degree_cent_q1',
 'degree_cent_q2',
 'degree_cent_q3',
 'degree_cent_skew',
 'degree_cent_std',
 'degree_iqr',
 'degree_max',
 'degree_mean',
 'degree_median',
 'degree_q1',
 'degree_q2',
 'degree_q3',
 'degree_skew',
 'degree_std',
 'distance_to_farthest_leaf',
 'distance_to_farthest_leaf_bucket',
 'distance_to_farthest_leaf_iqr',
 'distance_to_farthest_leaf_max',
 'distance_to_farthest_leaf_median',
 'distance_to_farthest_leaf_q1',
 'distance_to_farthest_leaf_q2',
 'distance_to_farthest_leaf_q3',
 'distance_to_farthest_leaf_skew',
 'distance_to_farthest_leaf_std',
 'distance_to_nearest_leaf_median',
 'distance_to_nearest_leaf_q3',
 'distance_to_nearest_leaf_std',
 'eccentricity',
 'eccentricity_iqr',
 'eccentricity_mean',
 'eccentricity_median',
 'eccentricity_q1',
 'eccentricity_q2',
 'eccentricity_q3',
 'eccentricity_skew',
 'effective_size',
 'effective_size_bucket',
 'effective_size_iqr',
 'effective_size_mean',
 'effective_size_median',
 'effective_size_q1',
 'effective_size_q2',
 'effective_size_q3',
 'effective_size_skew',
 'effective_size_std',
 'eigen_cent_median',
 'eigen_cent_q2',
 'eigen_cent_q3',
 'eigen_cent_skew',
 'eigen_cent_std',
 'graph_average_degree',
 'graph_avg_path_length',
 'graph_num_edges',
 'harmoni_cent',
 'harmoni_cent_bucket',
 'harmoni_cent_q2',
 'information_cent',
 'information_cent_bucket',
 'information_cent_iqr',
 'information_cent_mean',
 'information_cent_median',
 'information_cent_q1',
 'information_cent_q2',
 'information_cent_q3',
 'information_cent_skew',
 'information_cent_std',
 'is_centroid_iqr',
 'is_centroid_mean',
 'is_centroid_median',
 'is_centroid_std',
 'is_leaf_mean',
 'is_leaf_median',
 'is_leaf_q2',
 'is_leaf_q3',
 'katz_cent',
 'katz_cent_bucket',
 'katz_cent_iqr',
 'katz_cent_mean',
 'katz_cent_median',
 'katz_cent_q1',
 'katz_cent_q2',
 'katz_cent_q3',
 'katz_cent_skew',
 'katz_cent_std',
 'language_Arabic',
 'language_Chinese',
 'language_Finnish',
 'language_Hindi',
 'language_Japanese',
 'language_Korean',
 'language_Turkish',
 'language_group_Austronesian',
 'language_group_Kra-Dai',
 'language_group_Semitic',
 'largest_component_removed_bucket',
 'largest_component_removed_iqr',
 'largest_component_removed_max',
 'largest_component_removed_mean',
 'largest_component_removed_median',
 'largest_component_removed_q2',
 'largest_component_removed_q3',
 'largest_component_removed_std',
 'leaf_density_median',
 'load_centrality',
 'load_centrality_iqr',
 'load_centrality_mean',
 'load_centrality_median',
 'load_centrality_q1',
 'load_centrality_q2',
 'load_centrality_q3',
 'load_centrality_skew',
 'load_centrality_std',
 'max_distance_to_any_node_bucket',
 'max_distance_to_any_node_max',
 'max_distance_to_any_node_mean',
 'max_distance_to_any_node_median',
 'max_distance_to_any_node_q1',
 'max_distance_to_any_node_skew',
 'max_distance_to_any_node_std',
 'max_height',
 'max_height_bucket',
 'max_height_iqr',
 'max_height_max',
 'max_height_mean',
 'max_height_median',
 'max_height_q2',
 'max_height_q3',
 'max_height_skew',
 'max_height_std',
 'max_subtree_depth',
 'max_subtree_depth_bucket',
 'max_subtree_depth_iqr',
 'max_subtree_depth_mean',
 'max_subtree_depth_median',
 'max_subtree_depth_q1',
 'max_subtree_depth_q2',
 'max_subtree_depth_q3',
 'max_subtree_depth_skew',
 'max_subtree_depth_std',
 'max_subtree_size',
 'max_subtree_size_iqr',
 'max_subtree_size_mean',
 'max_subtree_size_median',
 'max_subtree_size_q1',
 'max_subtree_size_skew',
 'max_subtree_size_std',
 'min_subtree_depth',
 'min_subtree_depth_median',
 'min_subtree_depth_q1',
 'min_subtree_depth_q2',
 'min_subtree_depth_q3',
 'min_subtree_depth_skew',
 'min_subtree_size',
 'min_subtree_size_iqr',
 'min_subtree_size_mean',
 'min_subtree_size_median',
 'min_subtree_size_q3',
 'min_subtree_size_skew',
 'neighbor_degree_max_q2',
 'neighbor_degree_max_skew',
 'neighbor_degree_mean_q2',
 'neighbor_degree_mean_skew',
 'neighbor_degree_min_max',
 'neighbor_degree_min_median',
 'neighbor_degree_min_skew',
 'node_step_removal',
 'node_step_removal_bucket',
 'node_step_removal_iqr',
 'node_step_removal_q1',
 'node_step_removal_q2',
 'node_step_removal_skew',
 'node_step_removal_std',
 'num_leaf_neighbors_iqr',
 'num_leaf_neighbors_median',
 'num_leaf_neighbors_std',
 'num_subtrees',
 'num_subtrees_bucket',
 'num_subtrees_iqr',
 'num_subtrees_max',
 'num_subtrees_mean',
 'num_subtrees_median',
 'num_subtrees_q1',
 'num_subtrees_q2',
 'num_subtrees_q3',
 'num_subtrees_removed',
 'num_subtrees_removed_bucket',
 'num_subtrees_removed_iqr',
 'num_subtrees_removed_max',
 'num_subtrees_removed_mean',
 'num_subtrees_removed_median',
 'num_subtrees_removed_q1',
 'num_subtrees_removed_q2',
 'num_subtrees_skew',
 'num_subtrees_std',
 'page_cent',
 'page_cent_iqr',
 'page_cent_mean',
 'page_cent_median',
 'page_cent_q1',
 'page_cent_q2',
 'page_cent_q3',
 'page_cent_skew',
 'page_cent_std',
 'participation_diameter_max',
 'participation_diameter_q1',
 'participation_diameter_q2',
 'radiality',
 'radiality_q2',
 'second_order_cent',
 'second_order_cent_bucket',
 'second_order_cent_iqr',
 'second_order_cent_mean',
 'second_order_cent_median',
 'second_order_cent_q1',
 'second_order_cent_q2',
 'second_order_cent_q3',
 'second_order_cent_skew',
 'second_order_cent_std',
 'std_distance_to_leaf_nodes_max',
 'std_distance_to_leaf_nodes_median',
 'std_distance_to_leaf_nodes_q2',
 'std_distance_to_leaf_nodes_skew',
 'subgraph_cent',
 'subgraph_cent_iqr',
 'subgraph_cent_mean',
 'subgraph_cent_median',
 'subgraph_cent_q1',
 'subgraph_cent_q2',
 'subgraph_cent_q3',
 'subgraph_cent_skew',
 'subgraph_cent_std',
 'subtree_depth_balance',
 'subtree_depth_balance_bucket',
 'subtree_depth_balance_max',
 'subtree_depth_balance_q2',
 'subtree_depth_balance_q3',
 'subtree_depth_balance_skew',
 'subtree_depth_std',
 'subtree_depth_std_iqr',
 'subtree_depth_std_mean',
 'subtree_depth_std_median',
 'subtree_depth_std_q1',
 'subtree_depth_std_q2',
 'subtree_depth_std_skew',
 'subtree_depth_std_std',
 'subtree_size_balance',
 'subtree_size_balance_bucket',
 'subtree_size_balance_max',
 'subtree_size_balance_mean',
 'subtree_size_balance_q2',
 'subtree_size_balance_q3',
 'subtree_size_std_bucket',
 'subtree_size_std_iqr',
 'subtree_size_std_max',
 'subtree_size_std_mean',
 'subtree_size_std_median',
 'subtree_size_std_q1',
 'subtree_size_std_q2',
 'subtree_size_std_skew',
 'subtree_size_std_std',
 'subtree_size_variance',
 'subtree_size_variance_bucket',
 'subtree_size_variance_iqr',
 'subtree_size_variance_max',
 'subtree_size_variance_median',
 'subtree_size_variance_q1',
 'subtree_size_variance_q2',
 'subtree_size_variance_q3',
 'subtree_size_variance_skew',
 'vote_rank_score_mean',
 'vote_rank_score_q2',
 'vote_rank_score_q3',
 'vote_rank_score_std',
 'avg_distance_to_all_nodes_max',
'avg_distance_to_all_nodes_min',
'avg_distance_to_leaf_nodes_max',
'avg_distance_to_leaf_nodes_min',
'avg_shortest_path_length_max',
'avg_shortest_path_length_min',
'betweeness_cent_max',
'betweeness_cent_min',
'closeness_cent_max',
'closeness_cent_min',
'comm_betweenness_max',
'comm_betweenness_min',
'current_flow_betweenness_max',
'current_flow_betweenness_min',
'current_flow_closeness_min',
'degree_cent_max',
'degree_cent_min',
'degree_min',
'distance_to_farthest_leaf_min',
'distance_to_nearest_leaf_max',
'distance_to_nearest_leaf_min',
'eccentricity_max',
'eccentricity_min',
'effective_size_max',
'effective_size_min',
'eigen_cent_max',
'eigen_cent_min',
'harmoni_cent_max',
'harmoni_cent_min',
'information_cent_max',
'information_cent_min',
'is_centroid',
'is_centroid_bucket',
'is_centroid_max',
'is_centroid_min',
'is_centroid_q1',
'is_centroid_q2',
'is_leaf',
'is_leaf_iqr',
'is_leaf_max',
'is_leaf_min',
'is_leaf_q1',
'katz_cent_min',
'language_English',
'language_German',
'largest_component_removed_min',
'leaf_density_max',
'leaf_density_min',
'load_centrality_max',
'load_centrality_min',
'max_distance_to_any_node_min',
'max_height_min',
'max_subtree_depth_max',
'max_subtree_depth_min',
'max_subtree_size_max',
'max_subtree_size_min',
'min_subtree_depth_max',
'min_subtree_depth_min',
'min_subtree_size_max',
'min_subtree_size_min',
'neighbor_degree_max_max',
'neighbor_degree_max_min',
'neighbor_degree_mean_max',
'neighbor_degree_mean_min',
'neighbor_degree_min_min',
'node_step_removal_max',
'node_step_removal_min',
'num_leaf_neighbors_max',
'num_leaf_neighbors_min',
'num_leaf_neighbors_q1',
'num_leaf_neighbors_q2',
'num_subtrees_min',
'num_subtrees_removed_min',
'page_cent_max',
'page_cent_min',
'participation_diameter_min',
'participation_diameter_q3',
'radiality_max',
'radiality_min',
'second_order_cent_max',
'second_order_cent_min',
'std_distance_to_leaf_nodes_min',
'subgraph_cent_max',
'subgraph_cent_min',
'subtree_depth_balance_min',
'subtree_depth_std_max',
'subtree_depth_std_min',
'subtree_size_balance_min',
'subtree_size_std_min',
'subtree_size_variance_min',
'vote_rank_score_max',
'vote_rank_score_min',
'vote_rank_score_q1']



#                    'information_cent','current_flow_closeness',
#                    'avg_shortest_path_length','degree',
#  'eccentricity',
#  'degree_cent',
#  'load_centrality',
#  'comm_betweenness',
#  'betweeness_cent',
#  'katz_cent',
#  'effective_size',
#  'num_subtrees_removed',
#  'num_subtrees',
#  'largest_component_removed',
#  'max_subtree_size',
#  'subtree_size_std',
#  'max_height',
#  'max_distance_to_any_node',
#  'distance_to_farthest_leaf',
#  'max_subtree_depth',
#  'avg_distance_to_all_nodes',
#  'min_subtree_size',
#  'subtree_depth_balance',
#  'subtree_size_balance',
#  'graph_num_edges',
#  'graph_avg_path_length',
#  'graph_average_degree',
#  'language_group_Semitic',
#  'language_Chinese',
#  'language_group_Uralic',
#  'language_group_Indo-Aryan',
#  'language_group_Austronesian',
#  'language_group_Japonic',
#  'language_group_Koreanic',
#  'language_group_Kra-Dai',
#  'language_group_Turkic']

TEST_DROP_COLS = ['sentence','node_number','language','language_group','id',
'avg_distance_to_all_nodes',
 'avg_distance_to_all_nodes_bucket',
 'avg_distance_to_all_nodes_iqr',
 'avg_distance_to_all_nodes_mean',
 'avg_distance_to_all_nodes_median',
 'avg_distance_to_all_nodes_q1',
 'avg_distance_to_all_nodes_q2',
 'avg_distance_to_all_nodes_q3',
 'avg_distance_to_all_nodes_skew',
 'avg_distance_to_all_nodes_std',
 'avg_distance_to_leaf_nodes',
 'avg_distance_to_leaf_nodes_q2',
 'avg_shortest_path_length',
 'avg_shortest_path_length_bucket',
 'avg_shortest_path_length_iqr',
 'avg_shortest_path_length_q1',
 'avg_shortest_path_length_q2',
 'avg_shortest_path_length_q3',
 'avg_shortest_path_length_std',
 'betweeness_cent',
 'betweeness_cent_bucket',
 'betweeness_cent_iqr',
 'betweeness_cent_mean',
 'betweeness_cent_median',
 'betweeness_cent_q1',
 'betweeness_cent_q2',
 'betweeness_cent_q3',
 'betweeness_cent_skew',
 'closeness_cent',
 'closeness_cent_bucket',
 'closeness_cent_median',
 'closeness_cent_q2',
 'comm_betweenness',
 'comm_betweenness_bucket',
 'comm_betweenness_iqr',
 'comm_betweenness_mean',
 'comm_betweenness_median',
 'comm_betweenness_q1',
 'comm_betweenness_q2',
 'comm_betweenness_q3',
 'comm_betweenness_skew',
 'comm_betweenness_std',
 'current_flow_betweenness',
 'current_flow_betweenness_iqr',
 'current_flow_betweenness_mean',
 'current_flow_betweenness_median',
 'current_flow_betweenness_q1',
 'current_flow_betweenness_q2',
 'current_flow_betweenness_q3',
 'current_flow_betweenness_skew',
 'current_flow_betweenness_std',
 'current_flow_closeness',
 'current_flow_closeness_bucket',
 'current_flow_closeness_iqr',
 'current_flow_closeness_max',
 'current_flow_closeness_mean',
 'current_flow_closeness_median',
 'current_flow_closeness_q1',
 'current_flow_closeness_q2',
 'current_flow_closeness_q3',
 'current_flow_closeness_skew',
 'current_flow_closeness_std',
 'degree_bucket',
 'degree_cent',
 'degree_cent_iqr',
 'degree_cent_mean',
 'degree_cent_q1',
 'degree_cent_q2',
 'degree_cent_q3',
 'degree_cent_skew',
 'degree_cent_std',
 'degree_iqr',
 'degree_max',
 'degree_mean',
 'degree_median',
 'degree_q1',
 'degree_q2',
 'degree_q3',
 'degree_skew',
 'degree_std',
 'distance_to_farthest_leaf',
 'distance_to_farthest_leaf_bucket',
 'distance_to_farthest_leaf_iqr',
 'distance_to_farthest_leaf_max',
 'distance_to_farthest_leaf_median',
 'distance_to_farthest_leaf_q1',
 'distance_to_farthest_leaf_q2',
 'distance_to_farthest_leaf_q3',
 'distance_to_farthest_leaf_skew',
 'distance_to_farthest_leaf_std',
 'distance_to_nearest_leaf_median',
 'distance_to_nearest_leaf_q3',
 'distance_to_nearest_leaf_std',
 'eccentricity',
 'eccentricity_iqr',
 'eccentricity_mean',
 'eccentricity_median',
 'eccentricity_q1',
 'eccentricity_q2',
 'eccentricity_q3',
 'eccentricity_skew',
 'effective_size',
 'effective_size_bucket',
 'effective_size_iqr',
 'effective_size_mean',
 'effective_size_median',
 'effective_size_q1',
 'effective_size_q2',
 'effective_size_q3',
 'effective_size_skew',
 'effective_size_std',
 'eigen_cent_median',
 'eigen_cent_q2',
 'eigen_cent_q3',
 'eigen_cent_skew',
 'eigen_cent_std',
 'graph_average_degree',
 'graph_avg_path_length',
 'graph_num_edges',
 'harmoni_cent',
 'harmoni_cent_bucket',
 'harmoni_cent_q2',
 'information_cent',
 'information_cent_bucket',
 'information_cent_iqr',
 'information_cent_mean',
 'information_cent_median',
 'information_cent_q1',
 'information_cent_q2',
 'information_cent_q3',
 'information_cent_skew',
 'information_cent_std',
 'is_centroid_iqr',
 'is_centroid_mean',
 'is_centroid_median',
 'is_centroid_std',
 'is_leaf_mean',
 'is_leaf_median',
 'is_leaf_q2',
 'is_leaf_q3',
 'katz_cent',
 'katz_cent_bucket',
 'katz_cent_iqr',
 'katz_cent_mean',
 'katz_cent_median',
 'katz_cent_q1',
 'katz_cent_q2',
 'katz_cent_q3',
 'katz_cent_skew',
 'katz_cent_std',
 'language_Arabic',
 'language_Chinese',
 'language_Finnish',
 'language_Hindi',
 'language_Japanese',
 'language_Korean',
 'language_Turkish',
 'language_group_Austronesian',
 'language_group_Kra-Dai',
 'language_group_Semitic',
 'largest_component_removed_bucket',
 'largest_component_removed_iqr',
 'largest_component_removed_max',
 'largest_component_removed_mean',
 'largest_component_removed_median',
 'largest_component_removed_q2',
 'largest_component_removed_q3',
 'largest_component_removed_std',
 'leaf_density_median',
 'load_centrality',
 'load_centrality_iqr',
 'load_centrality_mean',
 'load_centrality_median',
 'load_centrality_q1',
 'load_centrality_q2',
 'load_centrality_q3',
 'load_centrality_skew',
 'load_centrality_std',
 'max_distance_to_any_node_bucket',
 'max_distance_to_any_node_max',
 'max_distance_to_any_node_mean',
 'max_distance_to_any_node_median',
 'max_distance_to_any_node_q1',
 'max_distance_to_any_node_skew',
 'max_distance_to_any_node_std',
 'max_height',
 'max_height_bucket',
 'max_height_iqr',
 'max_height_max',
 'max_height_mean',
 'max_height_median',
 'max_height_q2',
 'max_height_q3',
 'max_height_skew',
 'max_height_std',
 'max_subtree_depth',
 'max_subtree_depth_bucket',
 'max_subtree_depth_iqr',
 'max_subtree_depth_mean',
 'max_subtree_depth_median',
 'max_subtree_depth_q1',
 'max_subtree_depth_q2',
 'max_subtree_depth_q3',
 'max_subtree_depth_skew',
 'max_subtree_depth_std',
 'max_subtree_size',
 'max_subtree_size_iqr',
 'max_subtree_size_mean',
 'max_subtree_size_median',
 'max_subtree_size_q1',
 'max_subtree_size_skew',
 'max_subtree_size_std',
 'min_subtree_depth',
 'min_subtree_depth_median',
 'min_subtree_depth_q1',
 'min_subtree_depth_q2',
 'min_subtree_depth_q3',
 'min_subtree_depth_skew',
 'min_subtree_size',
 'min_subtree_size_iqr',
 'min_subtree_size_mean',
 'min_subtree_size_median',
 'min_subtree_size_q3',
 'min_subtree_size_skew',
 'neighbor_degree_max_q2',
 'neighbor_degree_max_skew',
 'neighbor_degree_mean_q2',
 'neighbor_degree_mean_skew',
 'neighbor_degree_min_max',
 'neighbor_degree_min_median',
 'neighbor_degree_min_skew',
 'node_step_removal',
 'node_step_removal_bucket',
 'node_step_removal_iqr',
 'node_step_removal_q1',
 'node_step_removal_q2',
 'node_step_removal_skew',
 'node_step_removal_std',
 'num_leaf_neighbors_iqr',
 'num_leaf_neighbors_median',
 'num_leaf_neighbors_std',
 'num_subtrees',
 'num_subtrees_bucket',
 'num_subtrees_iqr',
 'num_subtrees_max',
 'num_subtrees_mean',
 'num_subtrees_median',
 'num_subtrees_q1',
 'num_subtrees_q2',
 'num_subtrees_q3',
 'num_subtrees_removed',
 'num_subtrees_removed_bucket',
 'num_subtrees_removed_iqr',
 'num_subtrees_removed_max',
 'num_subtrees_removed_mean',
 'num_subtrees_removed_median',
 'num_subtrees_removed_q1',
 'num_subtrees_removed_q2',
 'num_subtrees_skew',
 'num_subtrees_std',
 'page_cent',
 'page_cent_iqr',
 'page_cent_mean',
 'page_cent_median',
 'page_cent_q1',
 'page_cent_q2',
 'page_cent_q3',
 'page_cent_skew',
 'page_cent_std',
 'participation_diameter_max',
 'participation_diameter_q1',
 'participation_diameter_q2',
 'radiality',
 'radiality_q2',
 'second_order_cent',
 'second_order_cent_bucket',
 'second_order_cent_iqr',
 'second_order_cent_mean',
 'second_order_cent_median',
 'second_order_cent_q1',
 'second_order_cent_q2',
 'second_order_cent_q3',
 'second_order_cent_skew',
 'second_order_cent_std',
 'std_distance_to_leaf_nodes_max',
 'std_distance_to_leaf_nodes_median',
 'std_distance_to_leaf_nodes_q2',
 'std_distance_to_leaf_nodes_skew',
 'subgraph_cent',
 'subgraph_cent_iqr',
 'subgraph_cent_mean',
 'subgraph_cent_median',
 'subgraph_cent_q1',
 'subgraph_cent_q2',
 'subgraph_cent_q3',
 'subgraph_cent_skew',
 'subgraph_cent_std',
 'subtree_depth_balance',
 'subtree_depth_balance_bucket',
 'subtree_depth_balance_max',
 'subtree_depth_balance_q2',
 'subtree_depth_balance_q3',
 'subtree_depth_balance_skew',
 'subtree_depth_std',
 'subtree_depth_std_iqr',
 'subtree_depth_std_mean',
 'subtree_depth_std_median',
 'subtree_depth_std_q1',
 'subtree_depth_std_q2',
 'subtree_depth_std_skew',
 'subtree_depth_std_std',
 'subtree_size_balance',
 'subtree_size_balance_bucket',
 'subtree_size_balance_max',
 'subtree_size_balance_mean',
 'subtree_size_balance_q2',
 'subtree_size_balance_q3',
 'subtree_size_std_bucket',
 'subtree_size_std_iqr',
 'subtree_size_std_max',
 'subtree_size_std_mean',
 'subtree_size_std_median',
 'subtree_size_std_q1',
 'subtree_size_std_q2',
 'subtree_size_std_skew',
 'subtree_size_std_std',
 'subtree_size_variance',
 'subtree_size_variance_bucket',
 'subtree_size_variance_iqr',
 'subtree_size_variance_max',
 'subtree_size_variance_median',
 'subtree_size_variance_q1',
 'subtree_size_variance_q2',
 'subtree_size_variance_q3',
 'subtree_size_variance_skew',
 'vote_rank_score_mean',
 'vote_rank_score_q2',
 'vote_rank_score_q3',
 'vote_rank_score_std',
 'avg_distance_to_all_nodes_max',
'avg_distance_to_all_nodes_min',
'avg_distance_to_leaf_nodes_max',
'avg_distance_to_leaf_nodes_min',
'avg_shortest_path_length_max',
'avg_shortest_path_length_min',
'betweeness_cent_max',
'betweeness_cent_min',
'closeness_cent_max',
'closeness_cent_min',
'comm_betweenness_max',
'comm_betweenness_min',
'current_flow_betweenness_max',
'current_flow_betweenness_min',
'current_flow_closeness_min',
'degree_cent_max',
'degree_cent_min',
'degree_min',
'distance_to_farthest_leaf_min',
'distance_to_nearest_leaf_max',
'distance_to_nearest_leaf_min',
'eccentricity_max',
'eccentricity_min',
'effective_size_max',
'effective_size_min',
'eigen_cent_max',
'eigen_cent_min',
'harmoni_cent_max',
'harmoni_cent_min',
'information_cent_max',
'information_cent_min',
'is_centroid',
'is_centroid_bucket',
'is_centroid_max',
'is_centroid_min',
'is_centroid_q1',
'is_centroid_q2',
'is_leaf',
'is_leaf_iqr',
'is_leaf_max',
'is_leaf_min',
'is_leaf_q1',
'katz_cent_min',
'language_English',
'language_German',
'largest_component_removed_min',
'leaf_density_max',
'leaf_density_min',
'load_centrality_max',
'load_centrality_min',
'max_distance_to_any_node_min',
'max_height_min',
'max_subtree_depth_max',
'max_subtree_depth_min',
'max_subtree_size_max',
'max_subtree_size_min',
'min_subtree_depth_max',
'min_subtree_depth_min',
'min_subtree_size_max',
'min_subtree_size_min',
'neighbor_degree_max_max',
'neighbor_degree_max_min',
'neighbor_degree_mean_max',
'neighbor_degree_mean_min',
'neighbor_degree_min_min',
'node_step_removal_max',
'node_step_removal_min',
'num_leaf_neighbors_max',
'num_leaf_neighbors_min',
'num_leaf_neighbors_q1',
'num_leaf_neighbors_q2',
'num_subtrees_min',
'num_subtrees_removed_min',
'page_cent_max',
'page_cent_min',
'participation_diameter_min',
'participation_diameter_q3',
'radiality_max',
'radiality_min',
'second_order_cent_max',
'second_order_cent_min',
'std_distance_to_leaf_nodes_min',
'subgraph_cent_max',
'subgraph_cent_min',
'subtree_depth_balance_min',
'subtree_depth_std_max',
'subtree_depth_std_min',
'subtree_size_balance_min',
'subtree_size_std_min',
'subtree_size_variance_min',
'vote_rank_score_max',
'vote_rank_score_min',
'vote_rank_score_q1']
#                   'information_cent','current_flow_closeness',
#                    'avg_shortest_path_length','eccentricity',
#  'degree_cent',
#  'load_centrality',
#  'comm_betweenness',
#  'betweeness_cent',
#  'katz_cent',
#  'degree',
#  'effective_size',
#  'num_subtrees_removed',
#  'num_subtrees',
#  'largest_component_removed',
#  'max_subtree_size',
#  'subtree_size_std',
#  'max_height',
#  'max_distance_to_any_node',
#  'distance_to_farthest_leaf',
#  'max_subtree_depth',
#  'avg_distance_to_all_nodes',
#  'min_subtree_size',
#  'subtree_depth_balance',
#  'subtree_size_balance',
#  'graph_num_edges',
#  'graph_avg_path_length',
#  'graph_average_degree',
#  'language_group_Semitic',
#  'language_Chinese',
#  'language_group_Uralic',
#  'language_group_Indo-Aryan',
#  'language_group_Austronesian',
#  'language_group_Japonic',
#  'language_group_Koreanic',
#  'language_group_Kra-Dai',
#  'language_group_Turkic']




